### ISSUE TITLE
Editing works locally, but not when deployed on Heroku

### ISSUE THREAD

**Issue by aoripov** [aoripov/JacobsMKT#7]

**Comment by schmollf** [comment]
It doesn't work for me locally.
<img width="1233" alt="screen shot 2015-07-10 at 07 46 17" src="https://cloud.githubusercontent.com/assets/10235118/8612853/d80b3f70-26d7-11e5-9653-f79aa7e8b480.png">

**Comment by aoripov** [comment]
I forgot to add edit.erb.html when commiting
